### ISSUE TITLE
Goggle Colab Not Working

### ISSUE THREAD

**Issue by slooi** [ChenyangQiQi/FateZero#21]
I'm getting a error when running:
`!accelerate launch test_fatezero.py --config=$CONFIG_NAME`

It seems like your are missing a file called `car-turn` in the `data` directory.
![image](https://github.com/ChenyangQiQi/FateZero/assets/36298969/d4ebe7e6-3132-4817-b903-c20f4f50215d)

Error:
```
Traceback (most recent call last):
  File "/content/FateZero/test_fatezero.py", line 286, in <module>
    run()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/content/FateZero/test_fatezero.py", line 259, in run
    test(config=config, **Omegadict)
  File "/content/FateZero/test_fatezero.py", line 141, in test
    video_dataset = ImageSequenceDataset(**dataset_config, prompt_ids=prompt_ids)
  File "/content/FateZero/video_diffusion/data/dataset.py", line 42, in __init__
    self.images = self.get_image_list(path)
  File "/content/FateZero/video_diffusion/data/dataset.py", line 143, in get_image_list
    for file in sorted(os.listdir(path)):
FileNotFoundError: [Errno 2] No such file or directory: 'data/car-turn'
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'test_fatezero.py', '--config=config/car-turn.yaml']' returned non-zero exit status 1.
```

**Comment by mayuelala** [comment]
maybe you could download the file from [here](https://github.com/ChenyangQiQi/FateZero/releases/download/v1.0.0/shape.zip)

**Comment by ChenyangQiQi** [comment]
Sorry about the problem. You may edit the path to VIDEO_FILE = 'data/teaser_car-turn'
